INSERT INTO GoodyHutSubTypes
		(GoodyHut,				SubTypeGoodyHut,				Description,									Weight,		ModifierID)
VALUES	('GOODYHUT_CULTURE',	'GOODYHUT_SAILOR_ONE_CIVIC',	'LOC_GOODYHUT_SAILOR_ONE_CIVIC_DESCRIPTION',	15,			'SAILOR_GOODY_CULTURE_GRANT_ONE_CIVIC');

INSERT INTO Modifiers (ModifierId, ModifierType)
VALUES	('SAILOR_GOODY_CULTURE_GRANT_ONE_CIVIC', 'MODIFIER_PLAYER_GRANT_RANDOM_CIVIC');

INSERT INTO ModifierArguments (ModifierId, Name, Value)
VALUES	('SAILOR_GOODY_CULTURE_GRANT_ONE_CIVIC', 'Amount', 1);